# Generated by Django 5.2.7 on 2025-11-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myassets', '0002_alter_tag_options_alter_asset_asset_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
