# Generated by Django 5.2.7 on 2025-11-03 19:41

import django.db.models.deletion
import myassets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myassets', '0003_asset_download_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('3d_model', '3D Model'), ('document', 'Document')], max_length=20),
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to=myassets.models.version_upload_path)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='myassets.asset')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version', '-created_at'],
                'unique_together': {('asset', 'version')},
            },
        ),
    ]
